var arr = ['a', 'b', 'c']
arr.unshift('1')
console.log(arr)
// arr.shift()
// arr.shift()
// console.log(arr)
// console.log(arr.slice(1, 2))
// console.log(arr)
// console.log(arr.splice(1, 2, 'aa', 'bb', 'cc'))
// console.log(arr)
// console.log(Object.prototype.toString.call(arr))
arr.splice(0, 1)
console.log(arr)